import{S as w,a as g,i as m}from"./assets/vendor-5401a4b0.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const o of r.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&l(o)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const C=new w(".images-container a",{captionsData:"alt"});function h(s){const t=document.querySelector(".images-container"),n=s.map(({largeImageURL:l,webformatURL:e,tags:r,likes:o,views:y,comments:L,downloads:b})=>`<div class="image-card">
    <div class="image">
      <a href="${l}">
      <img class="gallery-image" src="${e}" alt="${r}"/>
      </a>
   </div>
   <ul class="stats">
      <li class="stats-name">Likes<p class="numbers">${o}</p></li>
      <li class="stats-name">Views<p class="numbers">${y}</p></li>
      <li class="stats-name">Comments<p class="numbers">${L}</p></li>
      <li class="stats-name">Downloads<p class="numbers">${b}</p></li>
    </ul></div>`).join("");t.insertAdjacentHTML("beforeend",n),C.refresh()}g.defaults.baseURL="https://pixabay.com/api/";async function f(s,t){return(await g.get("",{params:{key:"42585608-470f45864f44da3a6987e4378",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}const u="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABHNCSVQICAgIfAhkiAAAAONJREFUSIm9lkESgyAMRT+dOhyr3kw9WdtjJVmkiw4OKgGU0sy4keT9MPiDgBFEMjOL1jxEMlucuwV3DhOAlyreVnEI5zARCbwfTKFD57muLtdcgVfXtsCLjF/ATVYOLiJjCZjK2TBz8NKuAiglwixPZlFT4NDJibV4PStggWrOLOQkjRaH98NMJKuZgK+xVLHUGKsosBcBgFo4ANxqklqiagdhNqliAc7NnqJADA/A+EyKIn/5TJnluU9oNdoq0H1UJF80RNeJ2vVO6Hqr5WoOPkjNnlw4hweA8cz42HTV+tvyAUq6NbiLrn50AAAAAElFTkSuQmCC",p=document.querySelector(".form"),A=document.querySelector(".images-container"),i=document.querySelector(".loader"),a=document.querySelector(".load-more-btn");let d=1,c;p.addEventListener("submit",S);a.addEventListener("click",v);async function S(s){if(s.preventDefault(),A.innerHTML=null,c=p.input.value.trim(),i.classList.remove("is-hidden"),!c){m.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",iconUrl:u,fontSize:"large",position:"topRight",messageColor:"white",titleColor:"white",theme:"dark",timeout:5e3,backgroundColor:"#EF4040",progressBar:!1}),i.classList.add("is-hidden");return}try{const t=await f(c);t.hits.length||m.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",iconUrl:u,fontSize:"large",position:"topRight",messageColor:"white",titleColor:"white",theme:"dark",timeout:5e3,backgroundColor:"#EF4040",progressBar:!1}),h(t.hits),i.classList.add("is-hidden"),a.classList.remove("is-hidden")}catch(t){console.log(t.message)}}async function v(){i.classList.remove("is-hidden"),a.classList.add("is-hidden"),d+=1;try{const s=await f(c,d),t=Math.ceil(s.totalHits/15);if(h(s.hits),O(),d>=t)return i.classList.add("is-hidden"),a.classList.add("is-hidden"),m.info({message:"We're sorry, but you've reached the end of search results."});i.classList.add("is-hidden"),a.classList.remove("is-hidden")}catch(s){console.log(s),console.log(s.message),i.classList.add("is-hidden")}}function O(){const s=A.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
