import{S as f,i as l}from"./assets/vendor-5b791d57.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const A=new f(".images-container a",{captionsData:"alt"});function p(a){const t=document.querySelector(".images-container"),s=a.map(({largeImageURL:o,webformatURL:e,tags:r,likes:i,views:m,comments:g,downloads:d})=>`<div class="image-card">
    <div class="image">
      <a href="${o}">
      <img class="gallery-image" src="${e}" alt="${r}"/>
      </a>
   </div>
   <ul class="stats">
      <li class="stats-name">Likes<p class="numbers">${i}</p></li>
      <li class="stats-name">Views<p class="numbers">${m}</p></li>
      <li class="stats-name">Comments<p class="numbers">${g}</p></li>
      <li class="stats-name">Downloads<p class="numbers">${d}</p></li>
    </ul></div>`).join("");t.insertAdjacentHTML("beforeend",s),A.refresh()}function h(a){const s=`https://pixabay.com/api/?${new URLSearchParams({key:"42585608-470f45864f44da3a6987e4378",q:a,image_type:"photo",orientation:"horizontal",safesearch:!0})}`;return fetch(s).then(o=>{if(!o.ok)throw new Error(o.statusText);return o.json()})}const c="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABHNCSVQICAgIfAhkiAAAAONJREFUSIm9lkESgyAMRT+dOhyr3kw9WdtjJVmkiw4OKgGU0sy4keT9MPiDgBFEMjOL1jxEMlucuwV3DhOAlyreVnEI5zARCbwfTKFD57muLtdcgVfXtsCLjF/ATVYOLiJjCZjK2TBz8NKuAiglwixPZlFT4NDJibV4PStggWrOLOQkjRaH98NMJKuZgK+xVLHUGKsosBcBgFo4ANxqklqiagdhNqliAc7NnqJADA/A+EyKIn/5TJnluU9oNdoq0H1UJF80RNeJ2vVO6Hqr5WoOPkjNnlw4hweA8cz42HTV+tvyAUq6NbiLrn50AAAAAElFTkSuQmCC",u=document.querySelector(".form"),y=document.querySelector(".images-container"),n=document.querySelector("span");u.addEventListener("submit",L);function L(a){a.preventDefault(),y.innerHTML=null;const t=u.input.value.trim();if(n.classList.add("loader"),!t){l.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",iconUrl:c,fontSize:"large",position:"topRight",messageColor:"white",titleColor:"white",theme:"dark",timeout:5e3,backgroundColor:"#EF4040",progressBar:!1}),n.classList.remove("loader");return}h(t).then(({hits:s})=>{s.length||l.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",iconUrl:c,fontSize:"large",position:"topRight",messageColor:"white",titleColor:"white",theme:"dark",timeout:5e3,backgroundColor:"#EF4040",progressBar:!1}),p(s),n.classList.remove("loader")})}
//# sourceMappingURL=commonHelpers.js.map
