import{S as w,a as g,i as m}from"./assets/vendor-5401a4b0.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&l(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const C=new w(".images-container a",{captionsData:"alt"});function h(t){const s=document.querySelector(".images-container"),o=t.map(({largeImageURL:l,webformatURL:e,tags:r,likes:a,views:y,comments:L,downloads:b})=>`<div class="image-card">
    <div class="image">
      <a href="${l}">
      <img class="gallery-image" src="${e}" alt="${r}"/>
      </a>
   </div>
   <ul class="stats">
      <li class="stats-name">Likes<p class="numbers">${a}</p></li>
      <li class="stats-name">Views<p class="numbers">${y}</p></li>
      <li class="stats-name">Comments<p class="numbers">${L}</p></li>
      <li class="stats-name">Downloads<p class="numbers">${b}</p></li>
    </ul></div>`).join("");s.insertAdjacentHTML("beforeend",o),C.refresh()}g.defaults.baseURL="https://pixabay.com/api/";async function f(t,s){const o=await g.get("",{params:{key:"42585608-470f45864f44da3a6987e4378",q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:15}});return console.log(o.data),o.data}const u="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABHNCSVQICAgIfAhkiAAAAONJREFUSIm9lkESgyAMRT+dOhyr3kw9WdtjJVmkiw4OKgGU0sy4keT9MPiDgBFEMjOL1jxEMlucuwV3DhOAlyreVnEI5zARCbwfTKFD57muLtdcgVfXtsCLjF/ATVYOLiJjCZjK2TBz8NKuAiglwixPZlFT4NDJibV4PStggWrOLOQkjRaH98NMJKuZgK+xVLHUGKsosBcBgFo4ANxqklqiagdhNqliAc7NnqJADA/A+EyKIn/5TJnluU9oNdoq0H1UJF80RNeJ2vVO6Hqr5WoOPkjNnlw4hweA8cz42HTV+tvyAUq6NbiLrn50AAAAAElFTkSuQmCC",p=document.querySelector(".form"),A=document.querySelector(".images-container"),i=document.querySelector(".loader"),n=document.querySelector(".load-more-btn");let d=1,c;p.addEventListener("submit",S);n.addEventListener("click",v);async function S(t){if(t.preventDefault(),A.innerHTML=null,c=p.input.value.trim(),i.classList.remove("is-hidden"),!c){m.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",iconUrl:u,fontSize:"large",position:"topRight",messageColor:"white",titleColor:"white",theme:"dark",timeout:5e3,backgroundColor:"#EF4040",progressBar:!1}),i.classList.add("is-hidden");return}try{const s=await f(c);s.hits.length||m.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",iconUrl:u,fontSize:"large",position:"topRight",messageColor:"white",titleColor:"white",theme:"dark",timeout:5e3,backgroundColor:"#EF4040",progressBar:!1}),h(s.hits),i.classList.add("is-hidden"),n.classList.remove("is-hidden")}catch(s){console.log(s.message)}}async function v(){i.classList.remove("is-hidden"),n.classList.add("is-hidden"),d+=1;try{const t=await f(c,d),s=Math.ceil(t.totalHits/15);if(h(t.hits),O(),d>=s)return i.classList.add("is-hidden"),n.classList.add("is-hidden"),m.info({message:"We're sorry, but you've reached the end of search results."});i.classList.add("is-hidden"),n.classList.remove("is-hidden")}catch(t){console.log(t),console.log(t.message),i.classList.add("is-hidden")}}function O(){const t=A.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
